MyAttendance/MyAttendance/Controllers/ManageRolesController.cs
using MyAttendance.Models.User;
using MyAttendance.Models.User.ViewModel;
using MyAttendance.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace MyAttendance.Controllers
{
    public class ManageRolesController : Controller
    {
        IRepository<UserModel> _userContext;
        IRepository<UserType> _userTypeContext;

        public ManageRolesController(IRepository<UserModel> _userContext,IRepository<UserType> _userType)
        {
            this._userContext = _userContext;
            this._userTypeContext = _userType;
        }
        // GET: ManageRoles
        public ActionResult Index()
        {
            var HODmodel =  (from u in _userContext.Collection()
                             join ut in _userTypeContext.Collection()
                             on u.UserTypeId equals ut.Id
                             where u.UserTypeId == 1
                             select new UserIndexViewModel()
                             {
                              Id = u.Id,
                              Email = u.Email,
                              Name = u.Name,
                              RoleType = ut.Type
                             });

            var teacherModel = (from u in _userContext.Collection()
                                join ut in _userTypeContext.Collection()
                                on u.UserTypeId equals ut.Id
                                where u.UserTypeId == 2
                                select new UserIndexViewModel()
                                {
                                    Id = u.Id,
                                    Email = u.Email,
                                    Name = u.Name,
                                    RoleType = ut.Type
                                });

            var studentModel = (from u in _userContext.Collection()
                                join ut in _userTypeContext.Collection()
                                on u.UserTypeId equals ut.Id
                                where u.UserTypeId == 3
                                select new UserIndexViewModel()
                                {
                                    Id = u.Id,
                                    Email = u.Email,
                                    Name = u.Name,
                                    RoleType = ut.Type
                                });
            var typeList = new UserTypeList()
            {
                Students = studentModel.ToList(),
                HOD = HODmodel.ToList(),
                Teacher = teacherModel.ToList()
            };

            return View(typeList);
        }

        public ActionResult AddTeacher()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTeacher(UserModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                bool repeatedEmail = _userContext.Collection().Any(x => x.Email == model.Email);
                if (repeatedEmail)
                {
                    ViewBag.Error = "Email is already taken";
                    return View(model);
                }
                else
                {
                    var teacherModel = new UserModel()
                    {
                        Name = model.Email,
                        Password = model.Password,
                        Address = model.Address,
                        Email = model.Address,
                        Gender = model.Gender,
                        UserTypeId = 2,
                        ConfirmPassword=model.ConfirmPassword
                    };
                    _userContext.Insert(teacherModel);
                    _userContext.Commit();
                    return RedirectToAction("Index");
                }
            }
            
        }

       
    }
}

MyAttendance/MyAttendance/Views/ManageRoles/AddTeacher.cshtml
@model MyAttendance.Models.User.UserModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
    <h4 style="text-align:center">ADD-TEACHER</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="input-field col s12">
        Enter Teacher Name :
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class="form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="input-field col s12">
        Enter Token Email:
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class="form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="input-field col s12">
        Enter Address:
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class="form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.RadioButtonFor(model => model.Gender, "Male", new { @id = "choice1" })

    <label for="choice1">Male</label>
    @Html.RadioButtonFor(model => model.Gender, "Female", new { @id = "choice2" })
    <label for="choice2">Female</label>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class="form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class="form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="input-field col s12">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ADD" class="btn btn-default" />
        </div>
    </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    $(document).ready(function () {
        $('.sLayout').removeClass('active');
        $('#roleManager').addClass('active');
    })
</script>

MyAttendance/MyAttendance/Views/ManageRoles/Index.cshtml
@model MyAttendance.Models.User.ViewModel.UserTypeList
<h2 style="text-align:center">
    Manage Roles
</h2>
<br/>
<div class="row">
    <div class="col s12">
    <ul id="tabs-swipe-demo" class="tabs">
        <li class="tab col s3"><a class="active" href="#test-swipe-1">HOD</a></li>
        <li class="tab col s3"><a href="#test-swipe-2">Teachers</a></li>
        <li class="tab col s3"><a href="#test-swipe-3">Students</a></li>
    </ul>
        </div>
    </div>
    
    <div id="test-swipe-1" class="col s12">
        <span>
            
    @Html.ActionLink(" ","","",null,new { @class="btn btn-primary fas fa-plus"})
            <label>ADD-HOD</label>
            </span>
        <table class="table table-bordered">
            <tr>
                <th>
                   Name
                </th>
                <th>
                    Email
                </th>
                <th>
                   Role Type
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model.HOD)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoleType)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info fa fa-edit " })

                    </td>
                </tr>
            }

        </table>
    </div>
    <div id="test-swipe-2" class="col s12">
        <span>

            @Html.ActionLink(" ", "AddTeacher", "ManageRoles", null, new { @class = "btn btn-primary fas fa-plus" })
            <label>ADD-TEACHER</label>
        </span>
        <table class="table table-bordered">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Role Type
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model.Teacher)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoleType)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info fa fa-edit " })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div id="test-swipe-3" class="col s12">
        <span>

            @Html.ActionLink(" ", "", "", null, new { @class = "btn btn-primary fas fa-plus" })
            <label>ADD-STUDENT</label>
        </span>
        <table class="table table-bordered">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Role Type
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model.Students)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoleType)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info fa fa-edit " })
                    </td>
                </tr>
            }

        </table>
    </div>

<script>
    $(document).ready(function () {
     
            $('.sLayout').removeClass('active');
            $('#roleManager').addClass('active');
       
        $('ul.tabs').tabs();

    });

    $(document).ready(function () {
        $('ul.tabs').tabs('select_tab', 'tab_id');
    });
</script>