MyAttendance/MyAttendance/Models/Attendance/Date.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace MyAttendance.Models.Attendance
{
    public class Date
    {
        public int Id { get; set; }
        [Required]
        [BindProperty]
        public DateTime date { get; set; }
        [Required]
        public int isHolidayFlag { get; set; }

       
    }
}

MyAttendance/MyAttendance/Models/Date.cs
namespace MyAttendance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Date
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Date()
        {
            StudentAttends = new HashSet<StudentAttend>();
        }

        public int Id { get; set; }

        public int isHolidayFlag { get; set; }

        [Column("date")]
        public DateTime date1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttend> StudentAttends { get; set; }
    }
}

MyAttendance/MyAttendance/Controllers/DateController.cs
using MyAttendance.Models.Attendance;
using MyAttendance.Repositories;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MyAttendance.Controllers
{
    [Authorize]
    public class DateController : Controller
    {
        // GET: Date
        IRepository<Date> _dateContext;
        public DateController(IRepository<Date> _dateContext)
        {
            this._dateContext = _dateContext;
        }


        public ActionResult Index()
        {

            return View();
        }

        public ActionResult RegisterToday()
        {
            var todayDate = DateTime.Now;
            bool registerCheck = _dateContext.Collection().Any(x => x.date.Date == todayDate.Date);
            if (registerCheck)
            {
                return RedirectToAction("EditRegistrationIndex");
            }
            else
            {
                return View();
            }

        }
        
        [HttpPost]
        public ActionResult RegisterToday(Date dateModel)
        {
            if (!ModelState.IsValid)
                return View();
            else
            {
                var model = new Date()
                {
                    date = DateTime.Now.Date,
                    isHolidayFlag = dateModel.isHolidayFlag
                };

                _dateContext.Insert(model);
                _dateContext.Commit();
                TempData.Clear();
                return RedirectToAction("Index", "Attendance");
            }

        }


        public ActionResult EditRegistrationIndex()
        {

            return View();
        }

        public ActionResult EditRegistration()
        {
            var model = _dateContext.Collection().Where(x => x.date == DateTime.Now.Date)
                                                 .FirstOrDefault();

            if (model == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(model);
            }
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditRegistration(Date date)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var datemodel = _dateContext.Collection().Where(x => x.date.Date == DateTime.Now.Date).FirstOrDefault();
                var model = new Date()
                {
                    Id = datemodel.Id,
                    date = datemodel.date,
                    isHolidayFlag = date.isHolidayFlag
                   
                };

                _dateContext.Detach(model);
                _dateContext.Edit(model);
                _dateContext.Commit();
                return RedirectToAction("Index", "Attendance");
            }
        }

        

      


       
    }
}

MyAttendance/MyAttendance/Views/Date/EditRegistration.cshtml
@model MyAttendance.Models.Attendance.Date


<h6>@TempData["Error"]</h6>
<h4 style="font-family:Candara">Registration Date - [@DateTime.Now.ToShortDateString()]</h4>
@using (Html.BeginForm())
{




    <hr />





    <h4>Today is:</h4>




    @Html.RadioButtonFor(model => model.isHolidayFlag, 1, new { @id = "choice1" })
    <label for="choice1">Holiday</label>

    @Html.RadioButtonFor(model => model.isHolidayFlag, 2, new { @id = "choice2" })
    <label for="choice2">WorkDay</label>




    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Submit" class="btn btn-danger" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    $(document).ready(function () {
        $('.sLayout').removeClass('active');
        $('#date').addClass('active');
    })
</script>

MyAttendance/MyAttendance/Views/Date/EditRegistrationIndex.cshtml
<h4 style="color:red;font-family:Candara">*Current Date is already Registered.</h4>

<br/>
<h4>Click below button to edit status</h4>
<br/>
<h6 style="font-family:Candara;font-style:italic;color:red">Note - *If attendance already submitted , then status can't be changed.</h6>
@Html.ActionLink("Edit-Registration", "EditRegistration",null,new { @class="btn btn-danger"})
<script>
    $(document).ready(function () {
        $('.sLayout').removeClass('active');
        $('#date').addClass('active');
    })
</script>

MyAttendance/MyAttendance/Views/Date/Index.cshtml
<div class="container">
    <h6 style="text-align:left;font-family:Cambria;color:#ff6a00">Registration Setting</h6>
    <br/>
    @Html.ActionLink("Register-Today", "RegisterToday", "Date", null, new { @class="btn btn-dark"})
</div>
<script>
    $(document).ready(function () 
    {
        $('.sLayout').removeClass("active");
        $('#Date').addClass("active");
    });

</script>

MyAttendance/MyAttendance/Views/Date/RegisterToday.cshtml
@model MyAttendance.Models.Attendance.Date
<style>
    [type="radio"]:not(:checked), [type="radio"]:checked {
        position: relative;
        opacity: 1;
    }
</style>

<h6>@TempData["Error"]</h6>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <h4 style="font-family:Candara">Registration Date - [@DateTime.Now.ToShortDateString()]</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <h4>Today is:</h4>



    @Html.RadioButtonFor(model => model.isHolidayFlag, 2, new { @id = "choice1" })
    <label for="choice1">WorkDay</label>




    @Html.RadioButtonFor(model => model.isHolidayFlag, 1, new { @id = "choice2" })
    <label for="choice2">HoliDay</label>
   




    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Submit" class="btn btn-danger" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    $(document).ready(function () {
        $('.sLayout').removeClass('active');
        $('#date').addClass('active');

    });
   
</script>